version: '3'
services:

  minio:
    image: minio/minio:latest
    hostname: minio
    command: server /export
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    volumes:
      - ./mnt/data:/data
    ports:
      - '9000:9000'

  forecaster:
    image: maxwie/iotlab:edge
    container_name: forecaster
    command: python main_edge.py --settings-file forecaster-configuration/settings.json
    volumes:
      - ./forecaster-configuration:/forecaster-configuration
    ports:
      - '443:443'