version: '3'
services:

  minio:
    image: minio/minio:latest
    hostname: minio
    container_name: minio
    command: server /export
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    volumes:
      - ./mnt/data:/data
    ports:
      - '9000:9000'

  mosquitto:
    image: toke/mosquitto:latest
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
    ports:
      - "1883:1883"

  forecaster:
    image: "${DOCKER_ID}/iotlab:edge-forecaster"
    hostname: forecaster
    container_name: forecaster
    command: python main.py edge --settings-file edge-configuration/settings.json
    volumes:
      - "./edge-configuration:${CONTAINER_APP_PATH}/edge-configuration"
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - minio
      - mosquitto