version: '3'
services:

  minio:
    image: minio/minio:latest
    hostname: minio
    container_name: minio
    command: server /export
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    volumes:
      - ./mnt/data:/data
    ports:
      - '9000:9000'

  forecaster:
    image: "${DOCKER_ID}/iotlab:edge-forecaster"
    hostname: forecaster
    container_name: forecaster
    command: python main.py --settings-file forecaster-configuration/settings.json
    volumes:
      - "./forecaster-configuration:${CONTAINER_APP_PATH}/forecaster-configuration"
    ports:
      - '443:443'
